version: '3.2'
services:
  gateway:
    image: tp/ehub-gateway
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - kafka
    networks:
      core:
        aliases:
          - gateway
  product-service:
    image: tp/product-service
    ports:
      - 8787:8787
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_NODES=redis://192.168.3.3:7000,redis://192.168.3.3:7001,redis://192.168.3.3:7002
    networks:
      core:
        aliases:
          - product-service
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      core:
        aliases:
          - zookeeper
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "commands:15:1,product-events:15:1,order-events:15:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      core:
        aliases:
          - kafka
networks:
  core:
    driver: bridge
