version: '3.2'
services:
  gateway:
    image: tp/gateway:latest
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_NODES=redis://redis:6379
    networks:
      core:
        aliases:
          - gateway
  product-service:
    image: tp/product-service:latest
    ports:
      - 8788:8787
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_NODES=redis://redis:6379
    networks:
      core:
        aliases:
          - product-service
  order-service:
    image: tp/order-service:latest
    ports:
      - 8787:8787
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_NODES=redis://redis:6379
    networks:
      core:
        aliases:
          - product-service
  views-service:
    image: tp/views-service:latest
    ports:
      - 8789:8789
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BROKERS=kafka:9092
      - REDIS_NODES=redis://redis:6379
    networks:
      core:
        aliases:
          - views-service
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      core:
        aliases:
          - redis
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      core:
        aliases:
          - zookeeper
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "product-commands:15:1,product-events:15:1,order-commands:15:1,order-events:15:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://kafka:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      core:
        aliases:
          - kafka
networks:
  core:
    driver: bridge
